/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BudgetUI;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.util.Comparator;
import javax.swing.JOptionPane;

/**
 *
 * @author melissacmitchell
 */

//creating, viewing, editing, and deleting transactions
public class EditTransactions extends javax.swing.JFrame {
    
    //creates model
    DefaultTableModel model; 
    
    //all transactions stored in array
    ArrayList<Transaction> transactions = new ArrayList<>();
    
    //defaults filter to all transactions
    DisplayFilter displayFilter = DisplayFilter.Both;
    
    //defaults categories to all categories
    boolean filterCategories = false;
    Category categoryFilter = null;
    
    //defaults month and year to all
    int monthToFilter = -1;
    int yearToFilter = -1;
    

    /**
     * Creates new form EditTransactions
     */
    public EditTransactions() {
        
        initComponents();

        //sets table columns
        model = new DefaultTableModel();
                    model.addColumn("Month");
                    model.addColumn("Year");
                    model.addColumn("Amount");
                    model.addColumn("Category");
                    model.addColumn("Recurring");
                    model.addColumn("#/Month");
                    
        //sets model  
        jTableTransactions.setModel(model);
        
        //sets column widths
        jTableTransactions.getColumnModel().getColumn(0).setPreferredWidth(125);
        jTableTransactions.getColumnModel().getColumn(1).setPreferredWidth(65);
        jTableTransactions.getColumnModel().getColumn(2).setPreferredWidth(125);
        jTableTransactions.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTableTransactions.getColumnModel().getColumn(4).setPreferredWidth(100);
        jTableTransactions.getColumnModel().getColumn(5).setPreferredWidth(100);
        
        //formats the money in the "amount" column of the table
        jTableTransactions.getColumnModel().getColumn(2).setCellRenderer(new CurrencyTableCellRenderer());
        
        readFromFile();
        updateDisplay();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxCategory = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldNumberPerMonth = new javax.swing.JTextField();
        jComboBoxSingleOrRecurring = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTransactions = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPrice = new javax.swing.JTextField();
        jButtonUpdate = new javax.swing.JButton();
        jButtonAddFilter = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonDelete = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonDone = new javax.swing.JButton();
        jComboBoxMonth = new javax.swing.JComboBox<>();
        jComboBoxYear = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxCategory.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBoxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bills and Utilities", "Kids", "Dining", "Groceries", "Entertainment", "Personal Care", "Health and Fitness", "Gifts and Donations", "Investments", "Miscellaneous" }));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("# per month");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Category");

        jTextFieldNumberPerMonth.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldNumberPerMonth.setText("1");
        jTextFieldNumberPerMonth.setEnabled(false);

        jComboBoxSingleOrRecurring.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBoxSingleOrRecurring.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes" }));
        jComboBoxSingleOrRecurring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSingleOrRecurringActionPerformed(evt);
            }
        });

        jTableTransactions.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTableTransactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Month", "Year", "Amount", "Category", "Recurring", "#/Month"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTransactions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTransactionsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTransactions);

        jLabel1.setFont(new java.awt.Font("Sitka Display", 1, 30)); // NOI18N
        jLabel1.setText("Transactions");

        jTextFieldPrice.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldPrice.setName("textBoxPrice"); // NOI18N

        jButtonUpdate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonAddFilter.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonAddFilter.setText("Add Filter");
        jButtonAddFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddFilterActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Month");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Price");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Year");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Recurring");

        jButtonDelete.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonAdd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonDone.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonDone.setText("Done");
        jButtonDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoneActionPerformed(evt);
            }
        });

        jComboBoxMonth.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBoxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jComboBoxMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMonthActionPerformed(evt);
            }
        });

        jComboBoxYear.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBoxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028" }));
        jComboBoxYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxYearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(334, 334, 334))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jButtonAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonUpdate))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel9))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldPrice, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldNumberPerMonth)
                                        .addComponent(jComboBoxSingleOrRecurring, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBoxMonth, javax.swing.GroupLayout.Alignment.LEADING, 0, 159, Short.MAX_VALUE)
                                        .addComponent(jComboBoxCategory, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE))
                                    .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jButtonDelete)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(237, 237, 237)
                                .addComponent(jButtonAddFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButtonDone, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBoxSingleOrRecurring, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldNumberPerMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButtonDone, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAddFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxSingleOrRecurringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSingleOrRecurringActionPerformed
        //enable or disenable the NumberPerMonth text field depending on whether the
        //transaction is recurring or single
        int selection = jComboBoxSingleOrRecurring.getSelectedIndex();

        if (selection == 0) {
            jTextFieldNumberPerMonth.setEnabled(false);
            jTextFieldNumberPerMonth.setText("1");
        } else {
            jTextFieldNumberPerMonth.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBoxSingleOrRecurringActionPerformed

    
    private void jTableTransactionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTransactionsMouseClicked
        
        //handles the user selecting a row in the table
        int numberOfRowsSelected = jTableTransactions.getSelectedRowCount();
        if (numberOfRowsSelected > 1) {
            clearDisplay();
            return;
        }
        
        int rowSelected = jTableTransactions.getSelectedRow();

        Transaction transaction = transactions.get(rowSelected);
        jComboBoxCategory.setSelectedItem(transaction.getCategory().toString());

        double transactionPrice;
        transactionPrice = transaction.getPrice();
        
        //sets text fields to the information from the selected row
        jTextFieldPrice.setText(String.format("%,.2f", transactionPrice));
        jComboBoxMonth.setSelectedItem(Conversions.convertMonthToString(transaction.getMonth()));
        jComboBoxYear.setSelectedItem(Integer.toString(transaction.getYear()));
        jComboBoxSingleOrRecurring.setSelectedItem(transaction.getRecurring() ? "Yes" : "No");
        jTextFieldNumberPerMonth.setText(Integer.toString(transaction.getEveryMonth()));
        
    }//GEN-LAST:event_jTableTransactionsMouseClicked

    
    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        
        //handles when the user presses the update button
        //checks how many rows are selected
        int rowCount = jTableTransactions.getSelectedRowCount();
        if (rowCount > 1) {
            //if more than one row is selected, informs user
            JOptionPane.showMessageDialog(null, "You can't update more then one row at a time.", "Invalid Update", 0);
            return;
        }
        
        //update entry
        int rowSelected = jTableTransactions.getSelectedRow();

        if (rowSelected == -1) {
            //if no rows are selected, exit
            return;
        }
        
        boolean updateFuture = false;
        
        //gets updated information
        Transaction transaction = getTransaction();
        
        //gets original information and removes data
        Transaction original = transactions.remove(rowSelected);
        
        //if selection acts on more than one transaction, ask the user what they want to do
        if (transaction.recurring || original.recurring) {
            String[] options = {"This One", "All Future", "Cancel"};
            int selection = JOptionPane.showOptionDialog(null, 
                    "Do you want to update only this transaction, or all future ones as well?", 
                    "Update Recurring Transaction", 
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null, 
                    options, 
                    options[0]);
           
            //if user decides to cancel, add the row back and exit
            if (selection == 2) {
                transactions.add(rowSelected, original);
                return;
                
            //if user decides to update all future selections, set flag to true
            } else if (selection == 1) {
                updateFuture = true;
            }
        }

        
        if (updateFuture) {
            //if the update flag is set and the original transaction is not 
            //recurring, create future transactions
            System.out.println("future me");
            if (!original.recurring) {
                System.out.println("Creating the future");
                transaction.createFuture(transactions);
            //otherwise the original is recurring
            } else {
                //if the new one is also recurring, undate the future transactions
                if (transaction.recurring) {
                    System.out.println("Updating the future");
                    transaction.updateFuture(transactions, original);
                    
                //otherwise delete the future transactions
                } else {
                    System.out.println("Destroying the future");
                    original.deleteFuture(transactions);
                }
            }
        }
        
        //make sure that the first transaction exists
        transactions.add(rowSelected, transaction);

        writeTransactions();
        clearDisplay();
        updateDisplay();
        
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    
    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed

        //get the number of selected rows
        int rowCount = jTableTransactions.getSelectedRowCount();
        
        //if there is more than one row while there are still rows, 
        //get the first selected row and deletes it
        if (rowCount > 1) {
            while (rowCount > 0) {
                int rowSelected = jTableTransactions.getSelectedRow();

                if (rowSelected >= 0) {
                    transactions.remove(rowSelected);
                    model.removeRow(rowSelected);
                }

                rowCount = jTableTransactions.getSelectedRowCount();
            } 
            
        //otherwise, determine if the transaction is recurring 
        } else {
            
            //get the currently selected row
            int rowSelected = jTableTransactions.getSelectedRow();
            
            //remove the transaction for the row
            Transaction transactionToDelete = transactions.remove(rowSelected);
            
            //if the transaction is recurring, ask the user what they want to do
            if (transactionToDelete.recurring) {
                String[] options = {"This One", "All Future", "Cancel"};
                int selection = JOptionPane.showOptionDialog(null, 
                        "Do you want to update only this transaction, or all future ones as well?", 
                        "Update Recurring Transaction", 
                        JOptionPane.DEFAULT_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null, 
                        options, 
                        options[0]);
                
                //if the user decides to cancel, add the transaction back and exit
                if (selection == 2) {
                    transactions.add(transactionToDelete);
                    return;
                    
                //if the user selects all future, delete the rest of the child transactions 
                } else if (selection == 1) {
                    transactionToDelete.deleteFuture(transactions);
                }
            }
        }
        
        writeTransactions();
        clearDisplay();
        updateDisplay();
        
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    
    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        
        //get the new transaction and create any future transactions as necessary
        Transaction transactionsToAdd = getTransaction();
        
        transactionsToAdd.createFuture(transactions);
        
        writeTransactions();
        updateDisplay();
        clearDisplay();
        
    }//GEN-LAST:event_jButtonAddActionPerformed

    
    private void jButtonDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoneActionPerformed

        //close form
        this.setVisible(false);
    }//GEN-LAST:event_jButtonDoneActionPerformed

    
    private void jButtonAddFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddFilterActionPerformed

        //create an instance of the View Remaining Money dialog
        AddFilters showDlg = new AddFilters(this, true);
        
        //display the child dialog
        showDlg.setVisible(true);
    }//GEN-LAST:event_jButtonAddFilterActionPerformed

    
    private void jComboBoxMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMonthActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxMonthActionPerformed

    
    private void jComboBoxYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxYearActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBoxYearActionPerformed

    
    private Transaction getTransaction() {
        
        //gets transaction from user input form
        Category category = Category.CreateFromString(jComboBoxCategory.getSelectedItem().toString());
        
        String priceString = jTextFieldPrice.getText();
        if (priceString.isEmpty()) {
            priceString = "0";
        }
        double price = new Double(priceString);
        
        int month = Conversions.convertStringToMonth((String) jComboBoxMonth.getSelectedItem());
        int year = new Integer((String)jComboBoxYear.getSelectedItem());
        
        System.out.println(String.valueOf(month));
        
        boolean recurring;
        String recurringString = jComboBoxSingleOrRecurring.getSelectedItem().toString();
        if(recurringString == "Yes"){
            recurring = true;
        }
        else {
            recurring = false;
        }
        
        int everyMonth = new Integer(jTextFieldNumberPerMonth.getText());
        
        Transaction transaction = new Transaction(category, price, month, year, recurring, everyMonth);

        return transaction;
        
    }

        
    //reads the transactions in from disk
    private void readFromFile(){
        
       transactions = FileIO.readTransactions();
       
       //if there are no transactions, create empty array
       if (transactions == null) {
           transactions = new ArrayList<>();
       }
       
    }
    
    
    //clear the text of an entry
    private void clearDisplay() {
        
        //sets user form back to default
        jTextFieldPrice.setText("");
        jComboBoxMonth.setSelectedIndex(0);
        jComboBoxYear.setSelectedIndex(0);
        jComboBoxSingleOrRecurring.setSelectedIndex(0);
        jTextFieldNumberPerMonth.setEnabled(false);
        jTextFieldNumberPerMonth.setText("1");
        
    }
    
    //sorts and filters the data and updates the display
    public void updateDisplay() {
        
        int count = model.getRowCount();
        
        //Remove all rows from existing table
        for (int removeItem = 0; removeItem < count; removeItem++) {
            model.removeRow(0);
        }

        //Goes through transactions and separates them based on selection
        for(Transaction transaction : transactions){
            if (Filters.passesTransactionFilter(transaction, displayFilter) &&
                    Filters.passesCategoryFilter(transaction, 
                            filterCategories ? categoryFilter : null) &&
                    Filters.passesMonthFilter(transaction, monthToFilter) &&
                    Filters.passesYearFilter(transaction, yearToFilter)) {
                
                // If the transaction passes all the filters, add it to the model
                model.addRow(new Object[]{
                    Conversions.convertMonthToString(transaction.getMonth()), 
                    transaction.getYear(), 
                    transaction.getPrice(), 
                    transaction.getCategory(), 
                    transaction.getRecurring() ? "Yes" : "No", 
                    transaction.getEveryMonth()});
            }
        }
    }
    
    
    private void writeTransactions() {
        //sorts the transactions
        transactions.sort(Comparator.comparing(Transaction::getYear)
                .thenComparing(Transaction::getMonth)
                .thenComparing(Transaction::getPrice)
                .thenComparing(Transaction::getCategory)
                .thenComparing(Transaction::getRecurring)
                .thenComparing(Transaction::getEveryMonth));
        
        //writes the sorted list to disk
        FileIO.writeTransactions(transactions);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditTransactions().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAddFilter;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonDone;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBoxCategory;
    private javax.swing.JComboBox<String> jComboBoxMonth;
    private javax.swing.JComboBox<String> jComboBoxSingleOrRecurring;
    private javax.swing.JComboBox<String> jComboBoxYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTransactions;
    private javax.swing.JTextField jTextFieldNumberPerMonth;
    private javax.swing.JTextField jTextFieldPrice;
    // End of variables declaration//GEN-END:variables

}
